alter table MUIPROMO.MENU
    ADD
        (
        TEMPLATE INTEGER
        );

CREATE SEQUENCE MUIPROMO.CONFIGURATION_SEQ
    MINVALUE 1
    MAXVALUE 2147483647
    START WITH 1000
    INCREMENT BY 1;

CREATE SEQUENCE MUIPROMO.CONNECTION_SETUP_SEQ
    MINVALUE 1
    MAXVALUE 2147483647
    START WITH 1
    INCREMENT BY 1;

ALTER SEQUENCE MUIPROMO.ACL_SEQ INCREMENT BY 1000;
ALTER SEQUENCE MUIPROMO.CONFIGURATION_SEQ INCREMENT BY 2000;
ALTER SEQUENCE MUIPROMO.CONNECTION_SETUP_SEQ INCREMENT BY 1000;
ALTER SEQUENCE MUIPROMO.MENU_ROLES_SEQ INCREMENT BY 1000;
ALTER SEQUENCE MUIPROMO.MENU_SEQ INCREMENT BY 1000;
ALTER SEQUENCE MUIPROMO.UI_SEQ INCREMENT BY 1000;
ALTER SEQUENCE MUIPROMO.USERS_SEQ INCREMENT BY 1000;