alter table MUIPROMO.USERS
    ADD
        (
        DESCRIPTION VARCHAR2(50)
        );

DROP SEQUENCE MUIPROMO.USERS_SEQ;

CREATE SEQUENCE MUIPROMO.USERS_SEQ
    MINVALUE 1
    MAXVALUE 2147483647
    START WITH 68
    INCREMENT BY 1;

