alter table MUIPROMO.CONFIGURATION add ID_MENU NUMBER(38,0);
alter table MUIPROMO.CONFIGURATION add LAST_REVISION_DATE TIMESTAMP;
alter table MUIPROMO.CONFIGURATION add LAST_EDITOR VARCHAR2(255);
drop index SQL190827184636951; -- remove unique constraint on path+type