alter table MUIPROMO.MENU
    ADD
        (
        TEMPLATE INTEGER
        );

CREATE SEQUENCE MUIPROMO.CONFIGURATION_SEQ
    MINVALUE 1
    MAXVALUE 2147483647
    START WITH 1000
    INCREMENT BY 1;

ALTER SEQUENCE MUIPROMO.MENU_SEQ INCREMENT BY 200;
select MUIPROMO.MENU_SEQ.nextval from dual;
ALTER SEQUENCE MUIPROMO.MENU_SEQ INCREMENT BY 1;