CREATE TABLE AUDIT_LOG(
LOG_DATE TIMESTAMP NOT NULL,
USERNAME VARCHAR2(50) NOT NULL,
ACTION VARCHAR2(50) NOT NULL,
PATH VARCHAR2(1000)
);
CREATE UNIQUE INDEX AUDIT_LOG_IDX ON AUDIT_LOG(LOG_DATE, USERNAME, ACTION);
CREATE INDEX AUDIT_LOG_PATH_IDX ON AUDIT_LOG(PATH);