--Administrator Role
INSERT INTO MUIPROMO.roles (ID, NAME, DESCRIPTION) VALUES (1, 'ADMIN', 'Administrator Role');
--Creating menu
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (1, null, 'Piano Annuale', null, null, 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (2, 1, 'Visualizza Piano', 'pianoAnnuale/visualizzaPiano.xhtml', 'agGrid', 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (3, 1, 'Modifica Promozione', 'pianoAnnuale/modificaPromozione.xhtml', 'agGrid', 2, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (4, 1, 'Crea Promozione', 'pianoAnnuale/creaPromozione.xhtml', 'agGrid', 3, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (5, 1, 'Timing', 'pianoAnnuale/timing.xhtml', 'agGrid', 4, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (6, 1, 'Meccaniche', 'pianoAnnuale/meccaniche.xhtml', 'agGrid', 5, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (7, 1, 'Meccaniche Set Complesse', 'pianoAnnuale/meccanicheSetComplesse.xhtml', 'agGrid', 6, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (8, 1, 'Zone Promo', 'pianoAnnuale/zonePromo.xhtml', 'agGrid', 7, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (9, 1, 'Sezioni Tematiche', 'pianoAnnuale/sezioniTematiche.xhtml', 'agGrid', 8, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (10, 1, 'Crea Sezione Tematica', 'pianoAnnuale/creaSezioneTematica.xhtml', 'agGrid', 9, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (11, 1, 'Negozi Promo', 'pianoAnnuale/negoziPromo.xhtml', 'agGrid', 10, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (12, 1, 'Controllo Negozi', 'pianoAnnuale/controlloNegozi.xhtml', 'agGrid', 11, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (13, 1, 'Foto', 'pianoAnnuale/foto.xhtml', 'agGrid', 12, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (14, 1, 'Gestione Contributi', 'pianoAnnuale/gestioneContributi.xhtml', 'agGrid', 13, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (15, 1, 'Gestione Iniziative', 'pianoAnnuale/gestioneIniziative.xhtml', 'agGrid', 14, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (16, 1, 'Gabbia', 'pianoAnnuale/gabbia.xhtml', 'agGrid', 15, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (17, null, 'Timone', null, null, 2, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (18, 17, 'Associazione Promo', 'timone/associazionePromo/associazionePromo.xhtml', 'agGrid', 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (19, 17, 'Target Reparto', null, null, 2, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (20, 19, 'Promo', 'timone/targetReparto/promo.xhtml', 'agGrid', 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (21, 19, 'Data', 'timone/targetReparto/data.xhtml', 'agGrid', 2, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (22, 17, 'Target Categoria', null, null, 3, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (23, 22, 'Promo', 'timone/targetCategoria/promo.xhtml', 'agGrid', 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (24, 22, 'Data', 'timone/targetCategoria/data.xhtml', 'agGrid', 2, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (25, 17, 'Foto Speciali', null, null, 4, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (26, 25, 'Target', 'timone/fotoSpeciali/target.xhtml', 'agGrid', 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (27, 25, 'Riepilogo', 'timone/fotoSpeciali/riepilogo.xhtml', 'agGrid', 2, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (28, 17, 'Spazi Campagna', null, null, 5, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (29, 28, 'Target Reparto', 'timone/spaziCampagna/targetReparto.xhtml', 'agGrid', 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (30, 28, 'Target Categoria', 'timone/spaziCampagna/targetCategoria.xhtml', 'agGrid', 2, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (31, null, 'Admin', null, null, 3, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (32, 31, 'Gestione Utenti', 'admin/gestioneUtenti.xhtml', 'gestioneUtenti', 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (33, 31, 'Gestione Ruoli', 'admin/gestioneRuoli.xhtml', 'gestioneRuoli', 2, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (34, 31, 'Gestione UI', 'admin/gestioneUI.xhtml', 'gestioneUI', 3, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (35, 31, 'Gestione ACL', 'admin/gestioneACL.xhtml', 'gestioneACL', 4, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (36, 17, 'Local Test', null, null, 6, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (37, 36, 'Local Test', 'gridcontentStreamed.xhtml', 'agGrid', 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (38, 36, 'Google.com', 'http://google.com', '', 2, 1);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (39, 9, 'Sezioni Tematiche', 'pianoAnnuale/sezioniTematiche/sezioniTematiche.xhtml', 'agGrid', 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (40, 9, 'Crea Sezioni Tematiche', 'pianoAnnuale/sezioniTematiche/creaSezioniTematiche.xhtml', 'agGrid', 2, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (41, 1, 'Spazi', null, null, 16, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (42, 41, 'Macro Spazi', 'pianoAnnuale/spazi/macroSpazi.xhtml', 'agGrid', 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (43, 41, 'Macrospazi Negozi', 'pianoAnnuale/spazi/macroSpaziNegozi.xhtml', 'agGrid', 2, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (44, 41, 'Macrospazi Negozi Promo', 'pianoAnnuale/spazi/macroSpaziNegoziPromo.xhtml', 'agGrid', 3, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (45, 41, 'Macrospazi Listino Promo', 'pianoAnnuale/spazi/macroSpaziListinoPromo.xhtml', 'agGrid', 4, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (46, 41, 'Spazi Condivisi', 'pianoAnnuale/spazi/spaziCondivisi.xhtml', 'agGrid', 5, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (47, 31, 'Gestione Menu', 'admin/gestioneMenu.xhtml', 'gestioneMenu', 5, 0);