INSERT INTO MUIPROMO.ACL (ID, ROLE_ID, UI_ID, COMPONENT_CLASS, COMPONENT, VISIBLE, EDITABLE, ENABLED) VALUES (200, 3, 21, 'BUTTON', 'pnf_aft_crea', 1, 0, 1);
INSERT INTO MUIPROMO.ACL (ID, ROLE_ID, UI_ID, COMPONENT_CLASS, COMPONENT, VISIBLE, EDITABLE, ENABLED) VALUES (201, 3, 21, 'BUTTON', 'pnf_aft_esegui', 1, 0, 1);
INSERT INTO MUIPROMO.ACL (ID, ROLE_ID, UI_ID, COMPONENT_CLASS, COMPONENT, VISIBLE, EDITABLE, ENABLED) VALUES (202, 3, 22, 'BUTTON', 'pnf_dif_inizializza', 1, 0, 1);
INSERT INTO MUIPROMO.ACL (ID, ROLE_ID, UI_ID, COMPONENT_CLASS, COMPONENT, VISIBLE, EDITABLE, ENABLED) VALUES (203, 3, 23, 'BUTTON', 'pnf_pro_abilita', 1, 0, 1);
INSERT INTO MUIPROMO.ACL (ID, ROLE_ID, UI_ID, COMPONENT_CLASS, COMPONENT, VISIBLE, EDITABLE, ENABLED) VALUES (204, 3, 23, 'BUTTON', 'pnf_pro_clear', 1, 0, 1);
INSERT INTO MUIPROMO.ACL (ID, ROLE_ID, UI_ID, COMPONENT_CLASS, COMPONENT, VISIBLE, EDITABLE, ENABLED) VALUES (205, 3, 23, 'BUTTON', 'pnf_pro_copia', 1, 0, 1);
INSERT INTO MUIPROMO.ACL (ID, ROLE_ID, UI_ID, COMPONENT_CLASS, COMPONENT, VISIBLE, EDITABLE, ENABLED) VALUES (206, 3, 23, 'BUTTON', 'pnf_pro_inizializza', 1, 0, 1);
INSERT INTO MUIPROMO.ACL (ID, ROLE_ID, UI_ID, COMPONENT_CLASS, COMPONENT, VISIBLE, EDITABLE, ENABLED) VALUES (207, 3, 23, 'BUTTON', 'pnf_pro_sposta', 1, 0, 1);
ALTER SEQUENCE MUIPROMO.ACL_SEQ INCREMENT BY 10;