SET DEFINE OFF;
UPDATE MUIPROMO.MENU SET ORDER_ID = 6 WHERE ID_MENU = 31;
UPDATE MUIPROMO.MENU SET ORDER_ID = 4 WHERE ID_MENU = 49;
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (60, null, 'Fatturazione', null, null, 3, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (61, 60, 'Contribuzione Campagna', 'fatturazione/contribuzioneCampagna.xhtml', 'agGrid', 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (62, 60, 'Associazioni Articoli', 'fatturazione/associazioneArticoli.xhtml', 'agGrid', 2, 0);

INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (63, null, 'Reporting TM1', null, null, 5, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (64, 63, 'Analisi Budget-Venduto', null, null, 1, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (65, 64, 'Categoria', 'http://tmonetest.mil.esselunga.net:9510/tm1web/UrlApi.jsp#Action=Open&Type=CubeViewer&Cube=Timone%20Reporting&View=(I)%20Timone%20Reporting%20-%20Buyer&AccessType=Public&AdminHost=tmonetest.mil.esselunga.net&TM1Server=Promo_Reporting', null, 1, 1);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (66, 64, 'Articolo', 'http://tmonetest.mil.esselunga.net:9510/tm1web/UrlApi.jsp#Action=Open&Type=CubeViewer&Cube=Reporting%20Articolo%20Zona&View=(I)%20Analisi%20BudgetVendutoArticolo&AccessType=Public&AdminHost=tmonetest.mil.esselunga.net&TM1Server=Promo_Reporting', null, 2, 1);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (67, 63, 'Storico articolo per zona (ACQ)', 'http://tmonetest.mil.esselunga.net:9510/tm1web/UrlApi.jsp#Action=Open&Type=CubeViewer&Cube=Reporting%20Articolo%20Zona&View=(I)%20Storico%20articolo%20per%20zona&AccessType=Public&AdminHost=tmonetest.mil.esselunga.net&TM1Server=Promo_Reporting', null, 2, 1);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (68, 63, 'Copia in Pianificazione', 'http://tmonetest.mil.esselunga.net:9510/tm1web/UrlApi.jsp#Action=Open&Type=CubeViewer&Cube=Reporting%20Articolo&View=(I)%20Copia%20in%20pianificazione&AccessType=Public&AdminHost=tmonetest.mil.esselunga.net&TM1Server=Promo_Reporting', null, 3, 1);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (69, 63, 'Sintesi Campagna', 'http://tmonetest.mil.esselunga.net:9510/tm1web/UrlApi.jsp#Action=Open&Type=CubeViewer&Cube=Timone%20Reporting&View=(I)%20Timone%20Reporting%20-%20Sintesi Campagna&AccessType=Public&AdminHost=tmonetest.mil.esselunga.net&TM1Server=Promo_Reporting', null, 4, 1);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (70, 63, 'Dettaglio Campagna', 'http://tmonetest.mil.esselunga.net:9510/tm1web/UrlApi.jsp#Action=Open&Type=CubeViewer&Cube=Reporting%20Articolo&View=(I)%20Dettaglio%20Campagna&AccessType=Public&AdminHost=tmonetest.mil.esselunga.net&TM1Server=Promo_Reporting', null, 5, 1);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (71, 63, 'Dettaglio Zona', 'http://tmonetest.mil.esselunga.net:9510/tm1web/UrlApi.jsp#Action=Open&Type=CubeViewer&Cube=Reporting%20Articolo%20Zona&View=(I)%20Dettaglio%20Zona&AccessType=Public&AdminHost=tmonetest.mil.esselunga.net&TM1Server=Promo_Reporting', null, 6, 1);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (72, 63, 'Timone Reparto', 'http://tmonetest.mil.esselunga.net:9510/tm1web/UrlApi.jsp#Action=Open&Type=CubeViewer&Cube=Timone%20Reparto&View=(II)%20Timone%20Reparto&AccessType=Public&AdminHost=tmonetest.mil.esselunga.net&TM1Server=Promo_Reporting', null, 7, 1);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (73, 63, 'Storico articolo per zona (MKT)', 'http://tmonetest.mil.esselunga.net:9510/tm1web/UrlApi.jsp#Action=Open&Type=CubeViewer&Cube=Reporting%20Articolo%20Zona&View=(I)%20Storico%20articolo%20per%20zona%20MKT&AccessType=Public&AdminHost=tmonetest.mil.esselunga.net&TM1Server=Promo_Reporting', null, 8, 1);
SET DEFINE ON;
