INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (91, 60, 'Contribuzione Promozioni', 'fatturazione/contribuzionePromozioni.xhtml', 'agGrid', 3, 0);

INSERT INTO MUIPROMO.ROLES (ID, NAME, DESCRIPTION) VALUES (2, 'UFF_PROMO', 'UFF_PROMO');
INSERT INTO MUIPROMO.ROLES (ID, NAME, DESCRIPTION) VALUES (3, 'UFF_IT', 'UFF_IT');
INSERT INTO MUIPROMO.ROLES (ID, NAME, DESCRIPTION) VALUES (4, 'CATEGORY ', 'CATEGORY');
INSERT INTO MUIPROMO.ROLES (ID, NAME, DESCRIPTION) VALUES (5, 'CAPOSETTORE ', 'CAPOSETTORE');
INSERT INTO MUIPROMO.ROLES (ID, NAME, DESCRIPTION) VALUES (6, 'COMPRATORE ', 'COMPRATORE');

INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (50, 'ICTKB0', '{}', 3, '[]', 1, 0, '{}', 'Katia Bresolin');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (51, 'ICTLT0', '{}', 3, '[]', 1, 0, '{}', 'Laura Taccia');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (52, 'ICTVA0', '{}', 3, '[]', 1, 0, '{}', 'Valerio Albano');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (53, 'ICTRA0', '{}', 3, '[]', 1, 0, '{}', 'Rossana Albertella');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (54, 'ICTGC1', '{}', 3, '[]', 1, 0, '{}', 'Giseppina Catania');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (55, 'CSLMC42', '{}', 3, '[]', 1, 0, '{}', 'Marta Coluzzi');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (56, 'CSLMR22', '{}', 3, '[]', 1, 0, '{}', 'Michelangelo Rossi');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (57, 'CSLIP3', '{}', 3, '[]', 1, 0, '{}', 'Ivan Pizzolante');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (58, 'TMONE01', '{}', 3, '[]', 1, 0, '{}', 'TMONE01');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (59, 'TMONE02', '{}', 2, '[]', 1, 0, '{}', 'TMONE02');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (60, 'TMONE03', '{}', 5, '[]', 1, 0, '{}', 'TMONE03');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (61, 'TMONE04', '{}', 4, '[]', 1, 0, '{}', 'TMONE04');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (62, 'TMONE05', '{}', 5, '[]', 1, 0, '{}', 'TMONE05');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (63, 'TMONE06', '{}', 6, '[]', 1, 0, '{}', 'TMONE06');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (64, 'TMONE07', '{}', 5, '[]', 1, 0, '{}', 'TMONE07');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (65, 'TMONE08', '{}', 4, '[]', 1, 0, '{}', 'TMONE08');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (66, 'TMONE09', '{}', 4, '[]', 1, 0, '{}', 'TMONE09');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS, ROLE_ID, HIDDEN_COLS, CAM_LOGIN, NAMESPACE_LOGIN, ADMIN_FILTERS, DESCRIPTION) VALUES (67, 'TMONE10', '{}', 4, '[]', 1, 0, '{}', 'TMONE10');

INSERT INTO "MUIPROMO"."MENU" (ID_MENU,PARENT_ID,LABEL,URL,BEAN,ORDER_ID,EXTERNAL_LINK) VALUES (92,31,'Gestione Log','/tracker/','',10,1);

UPDATE MUIPROMO.MENU SET BEAN = 'articoliFittizzi' WHERE ID_MENU = 77;
UPDATE MUIPROMO.MENU SET BEAN = 'differenziazionePromo' WHERE ID_MENU = 79;
UPDATE MUIPROMO.MENU SET BEAN = 'proiezioni' WHERE ID_MENU = 78;

DELETE FROM MUIPROMO.MENU WHERE LABEL LIKE '%Local%';
DELETE FROM MUIPROMO.MENU WHERE LABEL = 'Google.com';