SET DEFINE OFF;
UPDATE MUIPROMO.MENU SET ORDER_ID = 16 WHERE ID_MENU = 89;
UPDATE MUIPROMO.MENU SET ORDER_ID = 15 WHERE ID_MENU = 88;
UPDATE MUIPROMO.MENU SET ORDER_ID = 14 WHERE ID_MENU = 87;
UPDATE MUIPROMO.MENU SET ORDER_ID = 13 WHERE ID_MENU = 86;
UPDATE MUIPROMO.MENU SET ORDER_ID = 12 WHERE ID_MENU = 85;
UPDATE MUIPROMO.MENU SET ORDER_ID = 11 WHERE ID_MENU = 84;
UPDATE MUIPROMO.MENU SET ORDER_ID = 10 WHERE ID_MENU = 83;
UPDATE MUIPROMO.MENU SET ORDER_ID = 9 WHERE ID_MENU = 82;
UPDATE MUIPROMO.MENU SET ORDER_ID = 8 WHERE ID_MENU = 81;
UPDATE MUIPROMO.MENU SET ORDER_ID = 7 WHERE ID_MENU = 80;
UPDATE MUIPROMO.MENU SET ORDER_ID = 6 WHERE ID_MENU = 79;
UPDATE MUIPROMO.MENU SET ORDER_ID = 5 WHERE ID_MENU = 78;
UPDATE MUIPROMO.MENU SET ORDER_ID = 4 WHERE ID_MENU = 77;

INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (90, 74, 'Selezione Famiglie Contributi', 'proiezionePromo/selezioneFamiglieContributi.xhtml', 'agGrid', 3, 0);
SET DEFINE ON;