--Activate menu editing for Administrator Role
INSERT INTO MUIPROMO.menu_roles (ID, ID_MENU, ID_ROLES) VALUES (1, 31, 1);
INSERT INTO MUIPROMO.menu_roles (ID, ID_MENU, ID_ROLES) VALUES (2, 47, 1);
--Add Axiante users
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS,ROLE_ID,HIDDEN_COLS, CAM_LOGIN,NAMESPACE_LOGIN,ADMIN_FILTERS) VALUES (1,'CSLMF14', '{}', 1,'[]',1,0,'{}');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS,ROLE_ID,HIDDEN_COLS, CAM_LOGIN,NAMESPACE_LOGIN,ADMIN_FILTERS) VALUES (2,'CSLMM42', '{}', 1,'[]',1,0,'{}');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS,ROLE_ID,HIDDEN_COLS, CAM_LOGIN,NAMESPACE_LOGIN,ADMIN_FILTERS) VALUES (3,'CSLKR0', '{}', 1,'[]',1,0,'{}');
INSERT INTO MUIPROMO.USERS (ID, NAME, FILTERS,ROLE_ID,HIDDEN_COLS, CAM_LOGIN,NAMESPACE_LOGIN,ADMIN_FILTERS) VALUES (4,'CSLMG21', '{}', 1,'[]',1,0,'{}');