UPDATE MUIPROMO.MENU SET BEAN = 'spaziCampagneReparto' WHERE ID_MENU = 29;
UPDATE MUIPROMO.MENU SET BEAN = 'targetRepartoPromo' WHERE ID_MENU = 20;
UPDATE MUIPROMO.MENU SET BEAN = 'targetRepartoData' WHERE ID_MENU = 21;

DELETE FROM MUIPROMO.MENU_ROLES WHERE ID_MENU = 10;
DELETE FROM MUIPROMO.MENU WHERE ID_MENU = 10;
