UPDATE MUIPROMO.MENU SET BEAN = 'articoliFittizzi' WHERE ID_MENU = 77;
UPDATE MUIPROMO.MENU SET BEAN = 'differenziazionePromo' WHERE ID_MENU = 79;
UPDATE MUIPROMO.MENU SET BEAN = 'proiezioni' WHERE ID_MENU = 78;