INSERT INTO MUIPROMO.ROLES (ID, NAME, DESCRIPTION) VALUES (2, 'UFF_PROMO', 'UFF_PROMO');
INSERT INTO MUIPROMO.ROLES (ID, NAME, DESCRIPTION) VALUES (3, 'UFF_IT', 'UFF_IT');
INSERT INTO MUIPROMO.ROLES (ID, NAME, DESCRIPTION) VALUES (4, 'CATEGORY ', 'CATEGORY');
INSERT INTO MUIPROMO.ROLES (ID, NAME, DESCRIPTION) VALUES (5, 'CAPOSETTORE ', 'CAPOSETTORE');
INSERT INTO MUIPROMO.ROLES (ID, NAME, DESCRIPTION) VALUES (6, 'COMPRATORE ', 'COMPRATORE');

