INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (93, 31, 'Gestione Applicazione', 'admin/gestioneApplicazione.xhtml', 'gestioneApplicazione', 9, 0);

INSERT INTO MUIPROMO.APPLICATION_PROPERTIES (ID_APPLICATION_PROPERTIES, AP_KEY, AP_VALUE) VALUES (1, 'TOKEN_SPAWN', '120');
INSERT INTO MUIPROMO.APPLICATION_PROPERTIES (ID_APPLICATION_PROPERTIES, AP_KEY, AP_VALUE) VALUES (2, 'AUTH_SERVER', 'http://tmonetest.mil.esselunga.net');
INSERT INTO MUIPROMO.APPLICATION_PROPERTIES (ID_APPLICATION_PROPERTIES, AP_KEY, AP_VALUE) VALUES (3, 'MAX_CELLS', '100000');

INSERT INTO MUIPROMO.CONNECTION_SETUP (ID_CONNECTION_SETUP, CONNECTION_NAME, USERNAME, PASSWORD, DOMAIN, HOST, PORT, PATH, VALIDATE_SSL, AUTH_TYPE) VALUES (1, 'promo', null, null, null, 'https://TMONETEST', 8882, '/api/v1/', 0, 'PASSPORT');
INSERT INTO MUIPROMO.CONNECTION_SETUP (ID_CONNECTION_SETUP, CONNECTION_NAME, USERNAME, PASSWORD, DOMAIN, HOST, PORT, PATH, VALIDATE_SSL, AUTH_TYPE) VALUES (2, 'reporting', null, null, null, 'https://TMONETEST', 8883, '/api/v1/', 0, 'PASSPORT');

update MUIPROMO.MENU SET BEAN='agGrid' where PARENT_ID != 31 and BEAN is not null;