UPDATE MUIPROMO.APPLICATION_PROPERTIES SET AP_VALUE = 'http://tmoneprod.mil.esselunga.net' WHERE AP_KEY = 'AUTH_SERVER';

UPDATE MUIPROMO.CONNECTION_SETUP SET HOST = 'https://TMONEPROD' WHERE CONNECTION_NAME = 'promo';
UPDATE MUIPROMO.CONNECTION_SETUP SET HOST = 'https://TMONEPROD' WHERE CONNECTION_NAME = 'reporting';

UPDATE MUIPROMO.MENU
SET  URL = REPLACE( URL, 'tmonetest', 'tmoneprod')
WHERE URL LIKE '%tmonetest%';

