UPDATE MUIPROMO.MENU SET ORDER_ID = 8 WHERE LABEL LIKE 'Admin';
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (99, null, 'Controlli', null, null, 7, 0);
INSERT INTO MUIPROMO.MENU (ID_MENU, PARENT_ID, LABEL, URL, BEAN, ORDER_ID, EXTERNAL_LINK) VALUES (100, 99, 'Controlli Campagna MKTG', '', null, 1, 1);
