--clean up previous instances
DROP TABLE MUIPROMO.acl;
DROP SEQUENCE MUIPROMO.ACL_SEQ  ;
DROP TABLE MUIPROMO.users;
DROP SEQUENCE MUIPROMO.USERS_SEQ ;
DROP TABLE MUIPROMO.ui;
DROP SEQUENCE MUIPROMO.UI_SEQ ;
DROP TABLE MUIPROMO.menu_roles;
DROP SEQUENCE MUIPROMO.MENU_ROLES_SEQ ;
DROP TABLE MUIPROMO.roles;
DROP SEQUENCE MUIPROMO.ROLES_SEQ ;
DROP TABLE MUIPROMO.menu;
DROP SEQUENCE MUIPROMO.MENU_SEQ ;
DROP TABLE MUIPROMO.application_properties;
DROP TABLE MUIPROMO.configuration;
DROP TABLE MUIPROMO.connection_setup;
DROP SEQUENCE MUIPROMO.CONNECTION_SETUP_SEQ ;
DROP SCHEMA MUIPROMO ;
