  CREATE TABLE  RESTORE_TMP_CONSTRAINTS
   (	"OWNER" VARCHAR2(150 BYTE), 
	"TABLE_NAME" VARCHAR2(159 BYTE), 
	"CONSTRAINT_NAME" VARCHAR2(150 BYTE), 
	"CONSTRAINT_TYPE" VARCHAR2(2 BYTE), 
	"STATUS" VARCHAR2(10 BYTE)
   ) ;

   CREATE TABLE  BACKUP_LOG  
   (	
  "BACKUP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"BACKUP_DATE" DATE NOT NULL ENABLE, 
  "TABLE_NAME" VARCHAR2(250 BYTE) NOT NULL ENABLE
  ) ; 
  
  CREATE TABLE RESTORE_LOG 
   (	 
      "SAFE_BACKUP_ID" NUMBER(*,0) NOT NULL ENABLE, 
      "BACKUP_ID_RESTORED" NUMBER(*,0) NOT NULL ENABLE, 
    	"RESTORED_DATE" DATE NOT NULL ENABLE, 
	    "TABLE_NAME" VARCHAR2(250 BYTE) NOT NULL ENABLE
   )  ; 
   
   
  CREATE TABLE  ACL_BACKUP  
   (	
  "BACKUP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"BACKUP_DATE" DATE NOT NULL ENABLE, 
  "ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"UI_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"COMPONENT_CLASS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"COMPONENT" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"VISIBLE" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"EDITABLE" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"ENABLED" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE ) 
  ;
  
  
CREATE TABLE CONFIGURATION_BACKUP
   (	
     "BACKUP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"BACKUP_DATE" DATE NOT NULL ENABLE, 
   "ID_CONFIGURATION" NUMBER(*,0), 
	"PATH" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"JSON" CLOB NOT NULL ENABLE, 
	"TYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"ID_MENU" NUMBER(38,0), 
	"LAST_REVISION_DATE" TIMESTAMP (6), 
	"LAST_EDITOR" VARCHAR2(255 BYTE) )  ; 


  CREATE TABLE  MENU_BACKUP
   (	
    "BACKUP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"BACKUP_DATE" DATE NOT NULL ENABLE, 
   "ID_MENU" NUMBER(*,0) NOT NULL ENABLE, 
	"PARENT_ID" NUMBER(*,0), 
	"LABEL" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"URL" VARCHAR2(350 BYTE), 
	"BEAN" VARCHAR2(50 BYTE), 
	"ORDER_ID" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"EXTERNAL_LINK" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"TEMPLATE" NUMBER(*,0)
  ) ; 
  
  
   CREATE TABLE  MENU_ROLES_BACKUP
   (	
     "BACKUP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"BACKUP_DATE" DATE NOT NULL ENABLE, 
   "ID_MENU" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_ROLES" NUMBER(*,0) NOT NULL ENABLE
  )  ; 
  
    CREATE TABLE  ROLES_BACKUP 
   (	
   "BACKUP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"BACKUP_DATE" DATE NOT NULL ENABLE, 
   "ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"HELP_FILENAME" VARCHAR2(255 BYTE), 
	"HELP_DATA" BLOB )  ; 
  
  
CREATE TABLE  UI_BACKUP 
   (	
     "BACKUP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"BACKUP_DATE" DATE NOT NULL ENABLE, 
   "ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE)
  ) ;  
  
  