create or replace PROCEDURE P_CONFIG_BACKUP AS
v_BACKUP_ID     NUMBER ;
v_BACKUP_DATE  DATE ;
BEGIN
  v_BACKUP_DATE := SYSDATE ; 
  select USERS_BACKUP_SEQ.NEXTVAL  into v_BACKUP_ID from DUAL; 


/* ACL */ 
INSERT INTO ACL_BACKUP            (    BACKUP_ID,    BACKUP_DATE,    ID,    ROLE_ID,    UI_ID,    COMPONENT_CLASS,    COMPONENT,    VISIBLE,    EDITABLE,    ENABLED  )
SELECT v_BACKUP_ID as BACKUP_ID ,   v_BACKUP_DATE as BACKUP_DATE,    ID,    ROLE_ID,    UI_ID,    COMPONENT_CLASS,    COMPONENT,    VISIBLE,    EDITABLE,    ENABLED   
from ACL ; 

insert into BACKUP_LOG (   BACKUP_ID ,  BACKUP_DATE , TABLE_NAME  ) 
values (v_BACKUP_ID , v_BACKUP_DATE , 'ACL' ) ;

/* CONFIGURATION */ 
INSERT INTO CONFIGURATION_BACKUP   (    BACKUP_ID,    BACKUP_DATE,    ID_CONFIGURATION,    PATH,    JSON,    TYPE,    ID_MENU,    LAST_REVISION_DATE,    LAST_EDITOR  )
SELECT  v_BACKUP_ID as BACKUP_ID ,   v_BACKUP_DATE as BACKUP_DATE,    ID_CONFIGURATION,    PATH,    JSON,    TYPE,    ID_MENU,    LAST_REVISION_DATE,    LAST_EDITOR  
FROM CONFIGURATION ;  

insert into BACKUP_LOG (   BACKUP_ID ,  BACKUP_DATE , TABLE_NAME  ) 
values (v_BACKUP_ID , v_BACKUP_DATE , 'CONFIGURATION' ) ;

 
/* MENU */ 
INSERT INTO MENU_BACKUP           (    BACKUP_ID,    BACKUP_DATE,    ID_MENU,    PARENT_ID,    LABEL,    URL,    BEAN,    ORDER_ID,    EXTERNAL_LINK,    TEMPLATE  )
SELECT v_BACKUP_ID as BACKUP_ID ,   v_BACKUP_DATE as BACKUP_DATE,    ID_MENU,    PARENT_ID,    LABEL,    URL,    BEAN,    ORDER_ID,    EXTERNAL_LINK,    TEMPLATE
FROM MENU; 

insert into BACKUP_LOG (   BACKUP_ID ,  BACKUP_DATE , TABLE_NAME  ) 
values (v_BACKUP_ID , v_BACKUP_DATE , 'MENU' ) ;


/* MENU_ROLES */ 
INSERT INTO MENU_ROLES_BACKUP     (    BACKUP_ID,    BACKUP_DATE,    ID_MENU,    ID_ROLES  )
SELECT v_BACKUP_ID as BACKUP_ID ,   v_BACKUP_DATE as BACKUP_DATE ,   ID_MENU,    ID_ROLES 
FROM MENU_ROLES ; 

insert into BACKUP_LOG (   BACKUP_ID ,  BACKUP_DATE , TABLE_NAME  ) 
values (v_BACKUP_ID , v_BACKUP_DATE , 'MENU_ROLES' ) ;

/* ROLES */ 
INSERT INTO ROLES_BACKUP          (    BACKUP_ID,    BACKUP_DATE,    ID,    NAME,    DESCRIPTION,    HELP_FILENAME,    HELP_DATA  )
SELECT v_BACKUP_ID as BACKUP_ID ,   v_BACKUP_DATE as BACKUP_DATE,    ID,    NAME,    DESCRIPTION,    HELP_FILENAME,    HELP_DATA 
FROM ROLES ;

insert into BACKUP_LOG (   BACKUP_ID ,  BACKUP_DATE , TABLE_NAME  ) 
values (v_BACKUP_ID , v_BACKUP_DATE , 'ROLES' ) ;


/* UI */ 
INSERT INTO UI_BACKUP             (    BACKUP_ID,    BACKUP_DATE,    ID,    NAME,    DESCRIPTION  )
SELECT v_BACKUP_ID as BACKUP_ID ,   v_BACKUP_DATE as BACKUP_DATE,    ID,    NAME,    DESCRIPTION 
FROM UI ; 

insert into BACKUP_LOG (   BACKUP_ID ,  BACKUP_DATE , TABLE_NAME  ) 
values (v_BACKUP_ID , v_BACKUP_DATE , 'UI' ) ;


/* USERS */ 
INSERT INTO USERS_BACKUP             (   BACKUP_ID ,  BACKUP_DATE,   ID,  NAME,  FILTERS,  ROLE_ID,  HIDDEN_COLS,  CAM_LOGIN,  NAMESPACE_LOGIN,  ADMIN_FILTERS,  DESCRIPTION,  OLD_ROLE_ID) 
SELECT  v_BACKUP_ID as BACKUP_ID ,   v_BACKUP_DATE as BACKUP_DATE,   ID,  NAME,  FILTERS,  ROLE_ID,  HIDDEN_COLS,  CAM_LOGIN,  NAMESPACE_LOGIN,  ADMIN_FILTERS,  DESCRIPTION,  OLD_ROLE_ID
FROM USERS ;

insert into BACKUP_LOG (   BACKUP_ID ,  BACKUP_DATE , TABLE_NAME  ) 
values (v_BACKUP_ID , v_BACKUP_DATE , 'USERS' ) ;



/* ALL DONE */  

insert into BACKUP_LOG (   BACKUP_ID ,  BACKUP_DATE , TABLE_NAME  ) 
values (v_BACKUP_ID , v_BACKUP_DATE , '*' ) ;

COMMIT ; 


EXCEPTION  -- exception handlers begin
   WHEN OTHERS THEN  -- handles all other errors
      ROLLBACK;


END P_CONFIG_BACKUP;