package com.axiante.mui.webapp.views.content.enumeration;

public enum TabEnum {
	TAB_STATI, TAB_MECCANICHE, TAB_PROMO_RIFERIMENTO, TAB_PLANO_RIFERIMENTO, TAB_INIZIATIVA, TAB_NEGOZI,
	TAB_FLAG, TAB_ATTRIBUTI, TAB_TIPO_CASSA,
	TAB_REPARTI, TAB_PUBBLICAZIONI, TAB_OWNER, TAB_MARCHIO_PRIVATO,
	TAB_MODIFICA, TAB_CONTROLLI, TAB_COMPRATORI,
	TAB_PIANIFICAZIONE, TAB_COMPLEMENTARI, TAB_CONTROLLI_PIANIFICAZIONE, TAB_SOVRAPPOSIZIONI_PIANIFICAZIONE,
	TAB_INCLUSIONI_ESCLUSIONI, TAB_SOTTOSCRIZIONI
}
