CREATE SCHEMA DBPROMO 
CREATE TABLE DBPROMO.MUI_ASSORTIMENTO_FORNITORE (ID BIGINT NOT NULL , DATA_ELIMINAZIONE DATE, FORNITORE_PRINCIPALE DECIMAL(1) NOT NULL, ID_FORNITORE BIGINT NOT NULL, ID_ITEM BIGINT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_AUDIT_LOG (ID BIGINT NOT NULL , CODICE_UTENTE VARCHAR(50), DATA_ATTIVITA DATE, ID_PROMOZIONE DECIMAL(16), MESSAGE_LOG VARCHAR(2000), PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CANALE_LAST_PROG (ID BIGINT NOT NULL , ANNO DECIMAL(4) NOT NULL, LAST_PROGRESSIVO DECIMAL(8) NOT NULL, ID_CANALE BIGINT NOT NULL, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CANALE_PROMOZIONE (ID BIGINT NOT NULL , CODE_RANGE_MAX DECIMAL(8), CODE_RANGE_MIN DECIMAL(8), CODICE_CANALE DECIMAL(3) NOT NULL, DESCRIZIONE VARCHAR(30), SIGLA_CANALE VARCHAR(10), ID_GRUPPO BIGINT NOT NULL, FL_CHECK_DATE NUMERIC(1,0) NOT NULL DEFAULT 0, TOLLERANZA_DATA_FINE NUMERIC(3,0) NOT NULL DEFAULT 0, TOLLERANZA_DATA_INIZIO NUMERIC(3,0) NOT NULL DEFAULT 0, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CATEGORIA (ID BIGINT NOT NULL , CODICE_CATEGORIA VARCHAR(3) NOT NULL, DESCRIZIONE VARCHAR(30), ID_REPARTO BIGINT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CFG_ABILITA_MECC_CANALE (ID BIGINT NOT NULL , FLAG_ABILITA DECIMAL(1), FLAG_DEFAULT DECIMAL(1), ID_CANALE BIGINT NOT NULL, ID_MECCANICA BIGINT NOT NULL,  CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CFG_CANALE_NEGOZI (ID BIGINT NOT NULL , DEFAULT_FLAG VARCHAR(1), ID_CANALE BIGINT NOT NULL, ID_NEGOZIO BIGINT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CFG_PARAMETRI (ID BIGINT NOT NULL , CODICE_PARAMETRO VARCHAR(50) NOT NULL, DESCRIZIONE VARCHAR(255), VALORE VARCHAR(255), CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CFG_PIANIFICAZ_TIPO_RIGA (ID BIGINT NOT NULL , CODICE_TIPO VARCHAR(50) NOT NULL, DESCRIZIONE VARCHAR(255), CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CFG_PIANIFICAZIONE (ID BIGINT NOT NULL,LISTA_CONDIZIONALE VARCHAR(32672),CHIAVE VARCHAR(255), ABILITA_PER_TIPO_ELEMENTO VARCHAR(50),CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50),CODICE_UTENTE_INSERIMENTO VARCHAR(50),DESCRIZIONE VARCHAR(255),HIDE VARCHAR(1),LISTA VARCHAR(255),MANDATORY VARCHAR(1),ORDINAMENTO DECIMAL(8,0),SICUREZZA VARCHAR(1),TIPO_LISTA VARCHAR(255),UNIQUE_PERIODO_MECCANICA VARCHAR(1),UNIQUE_PROMO VARCHAR(1),WARN VARCHAR(1),ID_MUI_CFG_ABILITAZIONE_MC BIGINT,ID_TIPO_RIGA BIGINT,ID_PARENT BIGINT,ID_CAMPO BIGINT,ID_CFG_SET_PIANIFICAZIONE BIGINT,DEF_VALUE VARCHAR(255),DATA_INSERIMENTO TIMESTAMP,DATA_AGGIORNAMENTO TIMESTAMP,FLAG_MULTISELECT SMALLINT DEFAULT 0,"LENGTH" INTEGER DEFAULT NULL,UUID VARCHAR(32),ID_CFG_CONF_HEADER BIGINT,FORMAT_STRING VARCHAR(50),MIN_LENGTH BIGINT,ALLOW_ZERO INTEGER DEFAULT 0,VALIDO_SE_RAGGRUPPAMENTO BIGINT,LOOKUP_ATTRIBUTE VARCHAR(255) DEFAULT NULL,VALUE VARCHAR(255) DEFAULT NULL,VALUE_TYPE VARCHAR(255) DEFAULT NULL,FORMULA VARCHAR(4000) DEFAULT NULL,FORMULA_ENABLED DECIMAL(1,0) DEFAULT 0,PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CFG_PIANIFICAZIONE_CAMPI (ID BIGINT NOT NULL , CODICE_CAMPO VARCHAR(50) NOT NULL, DESCRIZIONE VARCHAR(255), DESCRIZIONE_ESTESA VARCHAR(500), RAGGRUPPAMENTO VARCHAR(50), TIPO VARCHAR(50), CAMPO VARCHAR(50), CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CFG_SET_PIANIFICAZIONE (ID BIGINT NOT NULL , DATA_FINE DATE, DATA_INIZIO DATE, DESCRIZIONE VARCHAR(255), ID_CFG_MECCANICA_CANALE DECIMAL(16) NOT NULL, LOCKED DECIMAL(1), CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CFG_STATI_CANALE_CONSENT (ID BIGINT NOT NULL , ID_CANALE BIGINT NOT NULL, ID_STATO BIGINT NOT NULL, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CFG_STATI_TRANSIZIONI (ID BIGINT NOT NULL , DESCRIZIONE VARCHAR(255), ID_CANALE BIGINT NOT NULL, ID_STATO_TRANSIZIONE BIGINT NOT NULL, ID_STATO BIGINT NOT NULL, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_COMPRATORE (ID BIGINT NOT NULL , CODICE_COMPRATORE VARCHAR(3) NOT NULL, DESCRIZIONE VARCHAR(20), FLAG_ATTIVO DECIMAL(1) NOT NULL, ID_RESPONSABILE BIGINT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_CREA_PROMOZIONE (ID BIGINT NOT NULL , ANNO VARCHAR(4), DATA_FINE DATE, DATA_INIZIO DATE, DESCRIZIONE VARCHAR(100), MESSAGGIO VARCHAR(2000), SLOT_ID VARCHAR(50) NOT NULL, USER_ID VARCHAR(50) NOT NULL, ID_CANALE BIGINT, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_FORNITORE (ID BIGINT NOT NULL , CODICE_FORNITORE VARCHAR(6) NOT NULL, DESCRIZIONE VARCHAR(30), PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_GRM (ID BIGINT NOT NULL , CODICE_GRM VARCHAR(3) NOT NULL, DESCRIZIONE VARCHAR(30), ID_CATEGORIA BIGINT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_GRUPPO_PROMOZIONE (ID BIGINT NOT NULL , CODICE_GRUPPO VARCHAR(4) NOT NULL, DESCRIZIONE VARCHAR(30), PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_ITEM (ID BIGINT NOT NULL , ATTIVO DECIMAL(1), ATTIVO_FI DECIMAL(1), ATTIVO_MI DECIMAL(1), CODICE_FAMIGLIA_AGGR VARCHAR(7), CODICE_ITEM VARCHAR(6) NOT NULL, CODICE_IVA DECIMAL(10,2), CODICE_MARCHIO_PRIVATO VARCHAR(2), COSTO_NETTO_GIORN DECIMAL(11,4), DATA_ELIMINAZIONE_FI DATE, DATA_ELIMINAZIONE_ITEM DATE, DATA_ELIMINAZIONE_MI DATE, DEALS_PROMOZIONALE DECIMAL(1), DESCRIZIONE VARCHAR(48), DESCRIZIONE_FAMIGLIA_AGGR VARCHAR(40), FL_PR_ATT_PROMO DECIMAL(1), FLAG_PESO DECIMAL(1), FUORI_STAGIONE DECIMAL(1), IN_OUT DECIMAL(1), MARCHIO_SL DECIMAL(1), NUMERO_NEGOZI DECIMAL(5), NUOVO DECIMAL(1), PEZZATURA DECIMAL(7), PREZZO_ATTUALE DECIMAL(9,2), PRODOTTO_PER_SL DECIMAL(1), SENZA_GLUTINE DECIMAL(1), STAGIONALE DECIMAL(1), STATUS DECIMAL(3), UNITA_MISURA VARCHAR(15), ID_COMPRATORE BIGINT NOT NULL, ID_SUBGRM BIGINT NOT NULL, FORMATO1 BIGINT, FORMATO2 BIGINT, FORMATO3 BIGINT, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_MECCANICHE (ID BIGINT NOT NULL , CODICE_MECCANICA VARCHAR(20) NOT NULL, DESCRIZIONE VARCHAR(80) NOT NULL, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_NEGOZIO (ID BIGINT NOT NULL , ACCETTA_ESPOSITORI DECIMAL(1), CEDI VARCHAR(2), CHIUSURA DATE, CHIUSURA_NON_DEFINITIVA DECIMAL(1), CODICE_APPOG_NEG_WEB VARCHAR(3), CODICE_CLUSTER DECIMAL(1) NOT NULL, CODICE_FORMATO VARCHAR(3) NOT NULL, CODICE_NEGOZIO VARCHAR(3) NOT NULL, CODICE_REP_INFOSTORE VARCHAR(3), CODICE_ZONA VARCHAR(2) NOT NULL, DESCRIZIONE VARCHAR(19), DESCRIZIONE_FORMATO VARCHAR(30), DESCRIZIONE_SOCIETA VARCHAR(30), DESCRIZIONE_ZONA VARCHAR(30), PUNTO_VENDITA_CHIUSO DECIMAL(1), REPARTO_AVF DECIMAL(1), REPARTO_PROFUMERIA DECIMAL(1), SOCIETA VARCHAR(1) NOT NULL, TIPO_NEGOZIO VARCHAR(50), ID_TIPO_NEGOZIO BIGINT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_PROCESS_LOG (ID BIGINT NOT NULL , DATA_FINE TIMESTAMP, DATA_INIZIO TIMESTAMP NOT NULL, DESCRIZIONE_ERRORE VARCHAR(4000), ESITO VARCHAR(3), PROCEDURA VARCHAR(255) NOT NULL, SEVERITY VARCHAR(20), PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_PROMO_COMPRATORE (ID BIGINT NOT NULL , FLAG_PIANIFICAZIONE_INIZIATA DECIMAL(1) NOT NULL, ID_COMPRATORE BIGINT NOT NULL, ID_PROMOZIONE BIGINT NOT NULL, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_PROMO_COMPRATORE_STATO (ID BIGINT NOT NULL , DATA_FINE_STATO DATE, DATA_INIZIO_STATO DATE NOT NULL, ID_PROMO_COMPRATORE BIGINT NOT NULL, ID_STATO BIGINT NOT NULL, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_PROMO_STATI_CONSENTITI (ID BIGINT NOT NULL , ID_PROMOZIONE BIGINT NOT NULL, ID_STATO BIGINT NOT NULL, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_PROMO_STATI_TRANSIZIONE (ID BIGINT NOT NULL , DESCRIZIONE VARCHAR(255), ID_PROMOZIONE BIGINT NOT NULL, ID_STATO BIGINT NOT NULL, ID_STATO_TRANSIZIONE BIGINT NOT NULL, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_PROMOZIONE_MECCANICHE (ID BIGINT NOT NULL , ID_MECCANICA BIGINT NOT NULL, ID_PROMOZIONE BIGINT NOT NULL, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_PROMOZIONE_NEGOZIO (ID BIGINT NOT NULL , DATA_FINE DATE, DATA_INIZIO DATE, DEFAULT_FLAG VARCHAR(1), SELEZIONE_FLAG VARCHAR(1), ID_NEGOZIO BIGINT NOT NULL, ID_PROMOZIONE BIGINT NOT NULL, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_PROMOZIONE_PIANIFICAZIONE (ID BIGINT NOT NULL , BUDGET_PEZZI VARCHAR(16), BUONO_SCONTO_PROGRESSIVO VARCHAR(16), BUONO_SCONTO_RADICE VARCHAR(16), CARTA_ORO VARCHAR(16), CARTA_ORO_PRIVILEGIATE VARCHAR(16), CARTA_VERDE VARCHAR(16), CARTA_VERDE_PRIVILEGIATE VARCHAR(16), CLASSE_DEFAULT VARCHAR(16), CODICE_COMPRATORE VARCHAR(3), CODICE_ELEMENTO VARCHAR(20), COMPRATORE VARCHAR(20), DATA_FINE DATE, DATA_FINE_BARCODE DATE, DATA_INIZIO DATE, DESCRIZIONE_SCONTO VARCHAR(16), ELEMENTO VARCHAR(30), ELENCO_CLUSTER VARCHAR(16), ESCLUSIONE VARCHAR(16), FASCIA_ORARIA VARCHAR(16), GENERA_BUONO_WEB VARCHAR(16), GIORNO_SETTIMANA VARCHAR(16), LETTERA_CODICE_ECOMMERCE VARCHAR(50), MAX_GIORNO VARCHAR(16), MAX_PERIODO VARCHAR(16), MAX_SCONTRINO VARCHAR(16), MOLTEPLICITA VARCHAR(16), NOTE_TIMING VARCHAR(255), NUM_RAGGRUPPAMENTO VARCHAR(16), NUM_SET VARCHAR(16), SCALA VARCHAR(16), STAMPA_OFFERTA VARCHAR(16), TARGET VARCHAR(16), TIPO_ELEMENTO VARCHAR(20), TIPO_RIGA VARCHAR(50), TIPO_SOGLIA VARCHAR(20), TIPO_TAGLIO VARCHAR(20), TIPO_TETTO VARCHAR(20), VALORE VARCHAR(16), VALORE_SCALA VARCHAR(16), VALORE_SOGLIA VARCHAR(16), VALORE_TAGLIO VARCHAR(16), VALORE_TETTO VARCHAR(16), ID_PROMOZIONE BIGINT NOT NULL, ID_MECCANICA BIGINT, NOTE VARCHAR(255), NUM_UTILIZZI VARCHAR(16), CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, STAMPA_ETICHETTA VARCHAR(16),ID_TIPO_RIGA BIGINT, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_PROMOZIONE_STATO (ID BIGINT NOT NULL , DATA_FINE_STATO DATE, DATA_INIZIO_STATO DATE, ID_PROMOZIONE BIGINT, ID_STATO BIGINT, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_PROMOZIONE_TESTATA (ID BIGINT NOT NULL , ANNO VARCHAR(4), CODICE_PROMOZIONE VARCHAR(10) NOT NULL, DATA_FINE DATE NOT NULL, DATA_INIZIO DATE NOT NULL, DESCRIZIONE VARCHAR(100), DESCRIZIONE_ESTESA VARCHAR(500), NOTE_MARKETING VARCHAR(2000), SEMESTRE VARCHAR(50), ID_CANALE BIGINT NOT NULL, ID_CFG_SET_PIANIFIC BIGINT, ID_CREA_PROMOZIONE BIGINT, CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), CODICE_UTENTE_INSERIMENTO VARCHAR(50), DATA_INSERIMENTO DATE, DATA_AGGIORNAMENTO DATE, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_REPARTO (ID BIGINT NOT NULL , CODICE_REPARTO VARCHAR(2) NOT NULL, DESCRIZIONE VARCHAR(30), CODICE_REPARTO_PADRE VARCHAR(2), PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_RESPONSABILE (ID BIGINT NOT NULL , CODICE_RESPONSABILE VARCHAR(4) NOT NULL, DESCRIZIONE VARCHAR(100), FLAG_ATTIVO DECIMAL(1) NOT NULL, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_SEC_ANNO (ID BIGINT NOT NULL , CODICE_ANNO VARCHAR(4), FLAG_ABILITA_VISUALIZZAZIONE DECIMAL(1), PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_SEC_ARTICOLO (ID BIGINT NOT NULL , CODICE_ARTICOLO VARCHAR(6), CODICE_USER_GROUP VARCHAR(50), PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_SEC_CANALE (ID BIGINT NOT NULL , CODICE_CANALE DECIMAL(3), CODICE_USER_GROUP VARCHAR(50), PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_SEC_COMPRATORE (ID BIGINT NOT NULL , CODICE_COMPRATORE VARCHAR(3), CODICE_USER_GROUP VARCHAR(50), PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_SEC_STATO (ID BIGINT NOT NULL , CODICE_STATO VARCHAR(4), CODICE_USER_GROUP VARCHAR(50), PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_STATO_PROMOZIONE (ID BIGINT NOT NULL , CODICE_STATO VARCHAR(4) NOT NULL, DESCRIZIONE VARCHAR(200) NOT NULL, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_SUB_GRM (ID BIGINT NOT NULL , CODICE_SUBGRM VARCHAR(3) NOT NULL, DESCRIZIONE VARCHAR(30), ID_GRM BIGINT NOT NULL, PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_TIPO_NEGOZIO (ID BIGINT NOT NULL , CODICE_TIPO_NEGOZIO VARCHAR(50) NOT NULL, DESCRIZIONE VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE DBPROMO.MUI_PROMO_PUBBLICAZ_TESTATA (	ID BIGINT NOT NULL, 	ID_PROMOZIONE BIGINT NOT NULL, 	ID_STATO BIGINT NOT NULL , 	DESCRIZIONE VARCHAR(20000), 	FLAG_ESITO INTEGER NOT NULL ,	DATA_PUBBLICAZIONE DATE NOT NULL , 	DATA_INSERIMENTO DATE, 	CODICE_UTENTE_INSERIMENTO VARCHAR(50), 	DATA_AGGIORNAMENTO DATE, 	CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50), PRIMARY KEY (ID)	)
CREATE TABLE DBPROMO.MUI_PROMO_PUBBLICAZ_COMPRATORE( ID bigint GENERATED BY DEFAULT AS IDENTITY ,CODICE_UTENTE_AGGIORNAMENTO varchar(50),CODICE_UTENTE_INSERIMENTO varchar(50),DATA_AGGIORNAMENTO date,DATA_INSERIMENTO date,DATA_PUBBLICAZIONE date NOT NULL,DESCRIZIONE varchar(2000),FLAG_ESITO decimal(1) NOT NULL,ID_PROMO_COMPRATORE bigint NOT NULL,ID_STATO_COMPRATORE bigint NOT NULL)
ALTER TABLE DBPROMO.MUI_PROMO_PUBBLICAZ_COMPRATORE ADD CONSTRAINT MPRMPBBLDPRMCMPRTR FOREIGN KEY (ID_PROMO_COMPRATORE) REFERENCES DBPROMO.MUI_PROMO_COMPRATORE(ID) 
ALTER TABLE DBPROMO.MUI_PROMO_PUBBLICAZ_COMPRATORE ADD CONSTRAINT MPRMPBBLDSTTCMPRTR FOREIGN KEY (ID_STATO_COMPRATORE) REFERENCES DBPROMO.MUI_PROMO_COMPRATORE_STATO(ID) 
CREATE UNIQUE INDEX SQL200612111528380 ON DBPROMO.MUI_PROMO_PUBBLICAZ_COMPRATORE(ID) 
CREATE INDEX SQL200612111529370 ON DBPROMO.MUI_PROMO_PUBBLICAZ_COMPRATORE(ID_PROMO_COMPRATORE) 
CREATE INDEX SQL200612111529390 ON DBPROMO.MUI_PROMO_PUBBLICAZ_COMPRATORE(ID_STATO_COMPRATORE)
ALTER TABLE DBPROMO.MUI_PROMO_PUBBLICAZ_TESTATA ADD CONSTRAINT  MUI_PROMO_PUBBLICAZ_TESTA_FK2 FOREIGN KEY (ID_STATO) REFERENCES MUI_STATO_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_PROMO_PUBBLICAZ_TESTATA ADD CONSTRAINT  MUI_PROMO_PUBBLICAZ_TESTA_FK1 FOREIGN KEY (ID_PROMOZIONE) REFERENCES MUI_PROMOZIONE_TESTATA (ID)
ALTER TABLE DBPROMO.MUI_ASSORTIMENTO_FORNITORE ADD CONSTRAINT MSSRTMNTFRNTDFRNTR FOREIGN KEY (ID_FORNITORE) REFERENCES MUI_FORNITORE (ID)
ALTER TABLE DBPROMO.MUI_ASSORTIMENTO_FORNITORE ADD CONSTRAINT MSSRTMNTFRNTOREDTM FOREIGN KEY (ID_ITEM) REFERENCES MUI_ITEM (ID)
ALTER TABLE DBPROMO.MUI_CANALE_LAST_PROG ADD CONSTRAINT MCNLELASTPROGDCNLE FOREIGN KEY (ID_CANALE) REFERENCES MUI_CANALE_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_CANALE_PROMOZIONE ADD CONSTRAINT MCNLPRMOZIONEDGRPP FOREIGN KEY (ID_GRUPPO) REFERENCES MUI_GRUPPO_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_CATEGORIA ADD CONSTRAINT MCATEGORIADREPARTO FOREIGN KEY (ID_REPARTO) REFERENCES MUI_REPARTO (ID)
ALTER TABLE DBPROMO.MUI_CFG_ABILITA_MECC_CANALE ADD CONSTRAINT MCFGBLTMCCCNDMCCNC FOREIGN KEY (ID_MECCANICA) REFERENCES MUI_MECCANICHE (ID)
ALTER TABLE DBPROMO.MUI_CFG_ABILITA_MECC_CANALE ADD CONSTRAINT MCFGBLTMCCCNLEDCNL FOREIGN KEY (ID_CANALE) REFERENCES MUI_CANALE_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_CFG_CANALE_NEGOZI ADD CONSTRAINT MCFGCNLENEGOZIDCNL FOREIGN KEY (ID_CANALE) REFERENCES MUI_CANALE_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_CFG_CANALE_NEGOZI ADD CONSTRAINT MCFGCNLENEGOZIDNGZ FOREIGN KEY (ID_NEGOZIO) REFERENCES MUI_NEGOZIO (ID)
ALTER TABLE DBPROMO.MUI_CFG_PIANIFICAZIONE ADD CONSTRAINT MCFGPNDCFGSTPNFCZN FOREIGN KEY (ID_CFG_SET_PIANIFICAZIONE) REFERENCES MUI_CFG_SET_PIANIFICAZIONE (ID)
ALTER TABLE DBPROMO.MUI_CFG_PIANIFICAZIONE ADD CONSTRAINT MCFGPNDMCFGBLTZNMC FOREIGN KEY (ID_MUI_CFG_ABILITAZIONE_MC) REFERENCES MUI_CFG_ABILITA_MECC_CANALE (ID)
ALTER TABLE DBPROMO.MUI_CFG_PIANIFICAZIONE ADD CONSTRAINT MCFGPNFCZIONEDPRNT FOREIGN KEY (ID_PARENT) REFERENCES MUI_CFG_PIANIFICAZIONE (ID)
ALTER TABLE DBPROMO.MUI_CFG_PIANIFICAZIONE ADD CONSTRAINT MCFGPNFCAZIONEDCMP FOREIGN KEY (ID_CAMPO) REFERENCES MUI_CFG_PIANIFICAZIONE_CAMPI (ID)
ALTER TABLE DBPROMO.MUI_CFG_PIANIFICAZIONE ADD CONSTRAINT MCFGPNFCZIONEDTPRG FOREIGN KEY (ID_TIPO_RIGA) REFERENCES MUI_CFG_PIANIFICAZ_TIPO_RIGA (ID)
ALTER TABLE DBPROMO.MUI_CFG_STATI_CANALE_CONSENT ADD CONSTRAINT MCFGSTTCNLCNSNDSTT FOREIGN KEY (ID_STATO) REFERENCES MUI_STATO_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_CFG_STATI_CANALE_CONSENT ADD CONSTRAINT MCFGSTTCNLCNSNDCNL FOREIGN KEY (ID_CANALE) REFERENCES MUI_CANALE_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_CFG_STATI_TRANSIZIONI ADD CONSTRAINT MCFGSTTTDSTTTRNSZN FOREIGN KEY (ID_STATO_TRANSIZIONE) REFERENCES MUI_STATO_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_CFG_STATI_TRANSIZIONI ADD CONSTRAINT MCFGSTTTRNSZNIDSTT FOREIGN KEY (ID_STATO) REFERENCES MUI_STATO_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_CFG_STATI_TRANSIZIONI ADD CONSTRAINT MCFGSTTTRNSZNIDCNL FOREIGN KEY (ID_CANALE) REFERENCES MUI_CANALE_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_COMPRATORE ADD CONSTRAINT MCMPRTREDRSPNSBILE FOREIGN KEY (ID_RESPONSABILE) REFERENCES MUI_RESPONSABILE (ID)
ALTER TABLE DBPROMO.MUI_CREA_PROMOZIONE ADD CONSTRAINT MCRPROMOZIONEDCNLE FOREIGN KEY (ID_CANALE) REFERENCES MUI_CANALE_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_GRM ADD CONSTRAINT MUIGRMID_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES MUI_CATEGORIA (ID)
ALTER TABLE DBPROMO.MUI_ITEM ADD CONSTRAINT MUI_ITEM_ID_SUBGRM FOREIGN KEY (ID_SUBGRM) REFERENCES MUI_SUB_GRM (ID)
ALTER TABLE DBPROMO.MUI_ITEM ADD CONSTRAINT MUIITEMDCOMPRATORE FOREIGN KEY (ID_COMPRATORE) REFERENCES MUI_COMPRATORE (ID)
ALTER TABLE DBPROMO.MUI_NEGOZIO ADD CONSTRAINT MNGOZIODTPONEGOZIO FOREIGN KEY (ID_TIPO_NEGOZIO) REFERENCES MUI_TIPO_NEGOZIO (ID)
ALTER TABLE DBPROMO.MUI_PROMO_COMPRATORE ADD CONSTRAINT MPRMCMPRTOREDPRMZN FOREIGN KEY (ID_PROMOZIONE) REFERENCES MUI_PROMOZIONE_TESTATA (ID)
ALTER TABLE DBPROMO.MUI_PROMO_COMPRATORE ADD CONSTRAINT MPRMCMPRTREDCMPRTR FOREIGN KEY (ID_COMPRATORE) REFERENCES MUI_COMPRATORE (ID)
ALTER TABLE DBPROMO.MUI_PROMO_COMPRATORE_STATO ADD CONSTRAINT MPRMCMPRTRSTTODSTT FOREIGN KEY (ID_STATO) REFERENCES MUI_STATO_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_PROMO_COMPRATORE_STATO ADD CONSTRAINT MPRMCMPRDPRMCMPRTR FOREIGN KEY (ID_PROMO_COMPRATORE) REFERENCES MUI_PROMO_COMPRATORE (ID)
ALTER TABLE DBPROMO.MUI_PROMO_STATI_CONSENTITI ADD CONSTRAINT MPRMSTTCNSNTTIDSTT FOREIGN KEY (ID_STATO) REFERENCES MUI_STATO_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_PROMO_STATI_CONSENTITI ADD CONSTRAINT MPRMSTTCNSNTDPRMZN FOREIGN KEY (ID_PROMOZIONE) REFERENCES MUI_PROMOZIONE_TESTATA (ID)
ALTER TABLE DBPROMO.MUI_PROMO_STATI_TRANSIZIONE ADD CONSTRAINT MPRMSTTTRNSZNEDSTT FOREIGN KEY (ID_STATO) REFERENCES MUI_STATO_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_PROMO_STATI_TRANSIZIONE ADD CONSTRAINT MPRMSTTTDSTTTRNSZN FOREIGN KEY (ID_STATO_TRANSIZIONE) REFERENCES MUI_STATO_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_PROMO_STATI_TRANSIZIONE ADD CONSTRAINT MPRMSTTTRNSZDPRMZN FOREIGN KEY (ID_PROMOZIONE) REFERENCES MUI_PROMOZIONE_TESTATA (ID)
ALTER TABLE DBPROMO.MUI_PROMOZIONE_MECCANICHE ADD CONSTRAINT MPRMZNMCCNCHDMCCNC FOREIGN KEY (ID_MECCANICA) REFERENCES MUI_MECCANICHE (ID)
ALTER TABLE DBPROMO.MUI_PROMOZIONE_MECCANICHE ADD CONSTRAINT MPRMZNMCCNCHDPRMZN FOREIGN KEY (ID_PROMOZIONE) REFERENCES MUI_PROMOZIONE_TESTATA (ID)
ALTER TABLE DBPROMO.MUI_PROMOZIONE_NEGOZIO ADD CONSTRAINT MPRMZNNGOZIODPRMZN FOREIGN KEY (ID_PROMOZIONE) REFERENCES MUI_PROMOZIONE_TESTATA (ID)
ALTER TABLE DBPROMO.MUI_PROMOZIONE_NEGOZIO ADD CONSTRAINT MPRMZNENEGOZIODNGZ FOREIGN KEY (ID_NEGOZIO) REFERENCES MUI_NEGOZIO (ID)
ALTER TABLE DBPROMO.MUI_PROMOZIONE_PIANIFICAZIONE ADD CONSTRAINT MPRMZNPNFCZNDPRMZN FOREIGN KEY (ID_PROMOZIONE) REFERENCES MUI_PROMOZIONE_TESTATA (ID)
ALTER TABLE DBPROMO.MUI_PROMOZIONE_STATO ADD CONSTRAINT MPRMZNESTATODPRMZN FOREIGN KEY (ID_PROMOZIONE) REFERENCES MUI_PROMOZIONE_TESTATA (ID)
ALTER TABLE DBPROMO.MUI_PROMOZIONE_STATO ADD CONSTRAINT MPRMZIONESTATODSTT FOREIGN KEY (ID_STATO) REFERENCES MUI_STATO_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_PROMOZIONE_TESTATA ADD CONSTRAINT MPRMZNTSTTDCRPRMZN FOREIGN KEY (ID_CREA_PROMOZIONE) REFERENCES MUI_CREA_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_PROMOZIONE_TESTATA ADD CONSTRAINT MPRMZNETESTATADCNL FOREIGN KEY (ID_CANALE) REFERENCES MUI_CANALE_PROMOZIONE (ID)
ALTER TABLE DBPROMO.MUI_PROMOZIONE_TESTATA ADD CONSTRAINT MPRMZNTSDCFGSTPNFC FOREIGN KEY (ID_CFG_SET_PIANIFIC) REFERENCES MUI_CFG_SET_PIANIFICAZIONE (ID)
ALTER TABLE DBPROMO.MUI_SUB_GRM ADD CONSTRAINT MUI_SUB_GRM_ID_GRM FOREIGN KEY (ID_GRM) REFERENCES MUI_GRM (ID)
CREATE SEQUENCE DBPROMO.MUI_PROMOZIONE_NEGOZIO_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CFG_STATI_TRANSIZIONI_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_GRM_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CFG_PIANIFICAZ_TIPO_RIGA_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_PROMO_COMPRATORE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CFG_ABILITA_MECC_CANALE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_COMPRATORE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CANALE_PROMOZIONE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_PROMOZIONE_STATO_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_SEC_CANALE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_PROMOZIONE_TESTATA_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_FORNITORE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CFG_PIANIFICAZIONE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_ITEM_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CANALE_LAST_PROG_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CFG_STATI_CANALE_CONSENT_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_SEC_COMPRATORE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CREA_PROMOZIONE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_RESPONSABILE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CFG_PARAMETRI_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CFG_SET_PIANIFICAZIONE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_REPARTO_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_SUB_GRM_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CFG_PIANIFICAZIONE_CAMPI_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CFG_CANALE_NEGOZI_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_SEC_ANNO_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_STATO_PROMOZIONE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_ASSORTIMENTO_FORNITORE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_SEC_ARTICOLO_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_SEC_STATO_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_AUDIT_LOG_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_GRUPPO_PROMOZIONE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_PROMO_COMPRATORE_STATO_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_CATEGORIA_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_PROMOZIONE_PIANIFICAZIONE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_MECCANICHE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_NEGOZIO_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_TIPO_NEGOZIO_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_PROMO_STATI_CONSENTITI_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_PROMO_STATI_TRANSIZIONE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_PROCESS_LOG_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_PROMOZIONE_MECCANICHE_ID_SEQ INCREMENT BY 1 START WITH 1
CREATE SEQUENCE DBPROMO.MUI_PROMOZIONE_TIPO_TERMINALE_ID_SEQ INCREMENT BY 1 START WITH 1
-- Fixes #3512
CREATE TABLE MUI_CFG_AZIONI(
	ID NUMERIC(16,0) NOT NULL PRIMARY KEY,
	CODICE VARCHAR(50),
	DESCRIZIONE VARCHAR(255)
);
CREATE SEQUENCE MUI_CFG_AZIONI_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE MUI_CFG_AZIONI_CONSENT(
	ID_STATO_CANALE BIGINT NOT NULL REFERENCES MUI_CFG_STATI_CANALE_CONSENT(ID),
	ID_AZIONE NUMERIC(16,0) NOT NULL REFERENCES MUI_CFG_AZIONI(ID)
);

CREATE TABLE V_MUI_PROMO_DBPROMO(
	CODICE_GRUPPO VARCHAR(4)	,
	CODICE_CANALE NUMERIC(3,0)	,
	CODICE_PROMOZIONE VARCHAR(10)	PRIMARY KEY ,
	DESCRIZIONE_ESTESA VARCHAR(134)	,
	DATA_INIZIO	DATE,
	DATA_FINE	DATE,
	SORGENTE_DATI CHAR(7)	
);

CREATE UNIQUE INDEX MUI_CFG_AZIONI_CONSENT_UNIQUE ON MUI_CFG_AZIONI_CONSENT(ID_STATO_CANALE, ID_AZIONE);

ALTER TABLE MUI_CFG_STATI_TRANSIZIONI ADD FLAG_PUBBLICA NUMERIC(1,0);
ALTER TABLE MUI_CFG_STATI_TRANSIZIONI ADD FLAG_CONTROLLA NUMERIC(1,0);
ALTER TABLE MUI_CFG_STATI_TRANSIZIONI ADD ID_STATO_ERRORE NUMERIC(1,0);

ALTER TABLE MUI_PROMO_STATI_TRANSIZIONE ADD FLAG_PUBBLICA NUMERIC(1,0);
ALTER TABLE MUI_PROMO_STATI_TRANSIZIONE ADD FLAG_CONTROLLA NUMERIC(1,0);
ALTER TABLE MUI_PROMO_STATI_TRANSIZIONE ADD ID_STATO_ERRORE NUMERIC(1,0);


CREATE TABLE DBPROMO.MUI_PROMOZIONE_REPARTO(ID_PROMOZIONE BIGINT NOT NULL, ID_REPARTO NOT NULL);
ALTER TABLE DBPROMO.MUI_PROMOZIONE_REPARTO ADD CONSTRAINT FKPROMOREPARTO1 FOREIGN KEY (ID_PROMOZIONE) REFERENCES DBPROMO.MUI_PROMOZIONE_TESTATA(ID); 
ALTER TABLE DBPROMO.MUI_PROMOZIONE_REPARTO ADD CONSTRAINT FKPROMOREPARTO2 FOREIGN KEY (ID_REPARTO) REFERENCES DBPROMO.MUI_REPARTO(ID) ;
CREATE UNIQUE INDEX MUI_PROMOZIONE_REPARTO_UNIQUE ON MUI_PROMOZIONE_REPARTO (ID_PROMOZIONE, ID_REPARTO) ;
CREATE TABLE DBPROMO.MUI_CHECK_TESTATA(ID NUMERIC(16,0) NOT NULL PRIMARY KEY,ID_PROMOZIONE BIGINT NOT NULL REFERENCES DBPROMO.MUI_PROMOZIONE_TESTATA(ID),TIPO_CONTROLLO VARCHAR(50),DESC_CONTROLLO VARCHAR(200),DESC_COMPRATORE VARCHAR(100),SEVERITA VARCHAR(50));
CREATE SEQUENCE MUI_CHECK_TESTATA_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE MUI_CHECK_COMPRATORI(ID NUMERIC(16,0) NOT NULL PRIMARY KEY,ID_PROMOZIONE BIGINT NOT NULL REFERENCES MUI_PROMOZIONE_TESTATA(ID),ID_COMPRATORE BIGINT NOT NULL REFERENCES MUI_COMPRATORE(ID),ESITO VARCHAR(50),CODICE_UTENTE_INSERIMENTO VARCHAR(50),CODICE_UTENTE_AGGIORNAMENTO VARCHAR(50),DATA_INSERIMENTO TIMESTAMP,DATA_AGGIORNAMENTO TIMESTAMP);
CREATE SEQUENCE MUI_CHECK_COMPRATORI_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE T_CONTRIBUTI_STATO_ANAG( COD_STATO_CONTR VARCHAR(4), DESCR_STATO_CONTR VARCHAR(255))
CREATE VIEW V_MUI_CONTRIBUTI_STATO_ANAG AS SELECT * FROM T_CONTRIBUTI_STATO_ANAG
CREATE TABLE T_PRESTAZIONI (COD_PRESTAZIONE	VARCHAR(6),COD_GRUPPO VARCHAR(4),DES_PRESTAZIONE VARCHAR(100),DES_FATTURA VARCHAR(255))
CREATE VIEW V_MUI_PRESTAZIONI AS SELECT * FROM T_PRESTAZIONI
CREATE TABLE DBPROMO.MUI_CONTRIBUTI_PROMO(ID NUMERIC(16,0) NOT NULL PRIMARY KEY,ID_PROMOZIONE NUMERIC(16,0) NOT NULL REFERENCES MUI_PROMOZIONE_TESTATA(ID),ID_COMPRATORE NUMERIC(16,0) NOT NULL REFERENCES MUI_COMPRATORE(ID),ID_FORNITORE NUMERIC(16,0) NOT NULL REFERENCES MUI_FORNITORE(ID),PROGRESSIVO NUMERIC(16,0),COD_PRESTAZIONE VARCHAR(6),VAL_APPLICATO NUMERIC(10,2),DATA_LIQUIDAZIONE DATE,NOTA_COMPRATORE VARCHAR(255),NOTA_FATTURA VARCHAR(255),COD_STATO_CONTR VARCHAR(4),SALDO_MOVIMENTI NUMERIC(10,2))
CREATE SEQUENCE DBPROMO.MUI_CONTRIBUTI_PROMO_SEQ START WITH 1 INCREMENT BY 1
CREATE TABLE DBPROMO.MUI_CONTRIBUTI_PROMO_ART(ID NUMERIC(16,0) NOT NULL PRIMARY KEY,ID_CONTRIBUTI_PROMO NUMERIC(16,0) NOT NULL REFERENCES MUI_CONTRIBUTI_PROMO(ID),ID_ITEM NUMERIC(16,0) NOT NULL REFERENCES MUI_ITEM(ID),WARN_FLAG NUMERIC(1,0))
CREATE SEQUENCE DBPROMO.MUI_CONTRIBUTI_PROMO_ART_SEQ START WITH 1 INCREMENT BY 1

CREATE TABLE T_TESTATA_PROMOZIONE (COD_PROMO VARCHAR(10), VALORE_PUNTO NUMERIC(3, 3), DATA_INIZIO TIMESTAMP, DATA_FINE TIMESTAMP);
CREATE VIEW V_MUI_GET_VALORE_PUNTO AS SELECT * FROM T_TESTATA_PROMOZIONE;

CREATE TABLE t_cluster_cliente(id_cluster varchar(50)  not null ,descrizione varchar(255),data_inizio date,data_fine date,data_aggiornamento timestamp);
create view v_mui_cluster_cliente as select * from t_cluster_cliente;
INSERT INTO t_cluster_cliente (id_cluster,descrizione,data_inizio,data_fine,data_aggiornamento) VALUES ('OVR65','Over 65',NULL,NULL,NULL);
INSERT INTO t_cluster_cliente (id_cluster,descrizione,data_inizio,data_fine,data_aggiornamento) VALUES ('STUD','Studenti',NULL,NULL,NULL);
INSERT INTO t_cluster_cliente (id_cluster,descrizione,data_inizio,data_fine,data_aggiornamento) VALUES ('FAM5+','Famiglia 5+',NULL,NULL,NULL);
INSERT INTO t_cluster_cliente (id_cluster,descrizione,data_inizio,data_fine,data_aggiornamento) VALUES ('UND14','Figli Under 14',NULL,NULL,NULL);

--5397
create table mui_font_entities(id_font_entities varchar(40) not null primary key,descrizione_entities varchar(255) not null);

